'\" t
.\"     Title: kerrighed
.\"    Author: [see the "Authors" section]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 06/07/2010
.\"    Manual: [FIXME: manual]
.\"    Source: [FIXME: source]
.\"  Language: English
.\"
.TH "KERRIGHED" "7" "06/07/2010" "[FIXME: source]" "[FIXME: manual]"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
kerrighed \- a Linux based Single System Image\&.
.SH "SYNOPSIS"
.HP \w'\fBKerrighed\fR\ 'u
\fBKerrighed\fR
.SH "DESCRIPTION"
.PP
Kerrighed is a Single System Image operating system for clusters\&. Kerrighed offers the view of a unique SMP machine on top of a cluster of standard PCs\&. Kerrighed main features are :
.PP
Configurable Global Process Scheduler:
.RS 4
Processes and threads are automatically scheduled over the cluster nodes to balance the CPU load using the Kerrighed default scheduling algorithm\&. However, Kerrighed offers a toolkit to easily write personal schedulers hot\-loadable through kernel modules\&.
.RE
.PP
Distributed Shared Memory:
.RS 4
Threads and System V memory segments can operate through the whole cluster, just like on a SMP machine\&.
.RE
.PP
High Performance Stream Migration Mechanism:
.RS 4
Processes using streams (socket, pipe, fifo, char device, etc) can be migrated with no penalty on communications performance\&.
.RE
.PP
Distributed File System:
.RS 4
A unique file name space is seen over the whole cluster\&. All nodes disk are merged in an unique global virtual disk\&.
.RE
.PP
Process Check\-pointing:
.RS 4
Processes can be check\-pointed and restarted on any cluster node\&.
.RE
.PP
Full System V Interface:
.RS 4
Full Posix Thread Interface\&.
.RE
.PP
Kerrighed is implemented as an extension to Linux operating system (a set of Linux modules and a small patch to the kernel)\&. Kerrighed is independent of the cluster interconnection network\&.
.SH "CONFIGURATION"
.PP
Kerrighed kernel is setup through boot parameters\&.
.SS "Boot parameters"
.PP
.PP
session_id=X
.RS 4
The
\fIsession_id\fR
contains identifier of the cluster\&. When several Kerrighed clusters have to share the same ethernet switch, each cluster should define a different session identifier to avoid collisions\&. A session identifier is a simple integer\&. Valid range is 1\&.\&.9999\&.
.sp
This parameter is mandatory\&.
.RE
.PP
node_id=Y
.RS 4
The
\fInode_id\fR
contains identifier of the node\&. It is an integer\&. It must be unique over the Kerrighed cluster\&. Valid range is 0\&.\&.255\&.
.sp
Unless
\fIautonodeid\fR
is activated this parameter is mandatory\&.
.RE
.PP
autonodeid=0|1
.RS 4
When
\fIautonodeid\fR
value is 1,
\fInode_id\fR
is the last digit of the IP address\&. This implies NIC driver to be compiled into the kernel and IP address to be set really early, either by DHCP or as kernel boot parameters (see
\fBbootparam\fR(7))\&.
.sp
Default is 1 (activated)\&.
.RE
.SH "AUTHORS"
.PP
Renaud Lottiaux
renaud\&.lottiaux@kerlabs\&.com
.PP
Jean Parpaillon
jean\&.parpaillon@kerlabs\&.com
.SH "SEE ALSO"
.PP

\m[blue]\fB\fBkerrighed_capabilities\fR (7)\fR\m[],
\m[blue]\fB\fBmigrate\fR (1)\fR\m[],
\m[blue]\fB\fBkrgcapset\fR (1)\fR\m[],
\m[blue]\fB\fBcheckpoint\fR (1)\fR\m[]
