'\" t
.\"     Title: krgcapset
.\"    Author: [see the "Author" section]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 06/07/2010
.\"    Manual: [FIXME: manual]
.\"    Source: [FIXME: source]
.\"  Language: English
.\"
.TH "KRGCAPSET" "1" "06/07/2010" "[FIXME: source]" "[FIXME: manual]"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
krgcapset \- Set or modify capabilities of a process\&.
.SH "SYNOPSIS"
.HP \w'\fBkrgcapset\fR\ 'u
\fBkrgcapset\fR [\-h | \-\-help]
.HP \w'\fBkrgcapset\fR\ 'u
\fBkrgcapset\fR \-v | \-\-version 
.HP \w'\fBkrgcapset\fR\ 'u
\fBkrgcapset\fR [{\-k\ |\ \-\-pid}\ \fIpid\fR] {\-s | \-\-show}
.HP \w'\fBkrgcapset\fR\ 'u
\fBkrgcapset\fR [\-f | \-\-force] [{\-k\ |\ \-\-pid}\ \fIpid\fR] {SET {[+\ |\ \-]\ CAPABILITY\ LIST  | OCTAL\ VALUE}...}
.SH "SET"
.PP
.PP
\-e, \-\-effective
.RS 4
Set up
\fBeffective\fR
capabilities\&.
.RE
.PP
\-p, \-\-permitted
.RS 4
Set up
\fBpermitted\fR
capabilities\&.
.RE
.PP
\-d, \-\-inheritable\-effective
.RS 4
Set up
\fBinheritable effective\fR
capabilities\&.
.RE
.PP
\-i, \-\-inheritable\-permitted
.RS 4
Set up
\fBinheritable permitted\fR
capabilities\&.
.RE
.SH "DESCRIPTION"
.PP
Kerrighed provides a system of
\fIcapabilities\fR, which allows administrator and users to define the way their processes behave in term of SSI mechanisms\&. Kerrighed cluster wide mechanisms are divided into distinct units that can be independently enabled and disabled\&. Each process has four capability sets:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBEffective\fR,
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBPermitted\fR,
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBInheritable Effective\fR,
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBInheritable Permitted\fR\&.
.RE
.PP
See
\fBkerrighed_capabilities\fR(7) for further details\&.
\fBkrgcapset\fR
modify calling process capabilities\&.
.SH "OPTIONS"
.PP
.PP
\-h, \-\-help
.RS 4
Print help and exit\&.
.RE
.PP
\-v, \-\-version
.RS 4
Print version information and exit\&.
.RE
.PP
\-k, \-\-pid \fIpid\fR
.RS 4
Act on the task having pid
\fIpid\fR\&. Default: act on calling process\&.
.RE
.PP
\-s, \-\-show
.RS 4
Show the capabilities of the designated process\&.
.RE
.PP
\-f, \-\-force
.RS 4
Do not ask for confirmation when removing CHANGE_KERRIGHED_CAP\&.
.RE
.SH "EXAMPLES"
.PP
.PP
krgcapset \-\-show
.RS 4
Show capabilities of the calling process\&.
.RE
.PP
krgcapset \-\-effective +CAN_MIGRATE
.RS 4
Add the "CAN_MIGRATE" effective capability to the calling process\&.
.RE
.PP
krgcapset \-\-effective \-CAN_MIGRATE
.RS 4
Remove the "CAN_MIGRATE" effective capability to the calling process\&.
.RE
.PP
krgcapset \-\-effective 07
.RS 4
Set effective capabilities to CHANGE_KERRIGHED_CAP, USE_CONTAINERS, CAN_MIGRATE\&.
.RE
.SH "AUTHOR"
.PP
Renaud Lottiaux
renaud\&.lottiaux@kerlabs\&.com
.SH "SEE ALSO"
.PP

\m[blue]\fB\fBkerrighed_capabilities\fR(7)\fR\m[]
