--- ipc/Makefile
+++ ipc/Makefile
@@ -9,4 +9,5 @@
 obj-$(CONFIG_POSIX_MQUEUE) += mqueue.o msgutil.o $(obj_mq-y)
 obj-$(CONFIG_IPC_NS) += namespace.o
 obj-$(CONFIG_POSIX_MQUEUE_SYSCTL) += mq_sysctl.o
-
+obj-$(CONFIG_KRG_IPC) += ipcmap_io_linker.o ipc_handler.o msg_io_linker.o msg_handler.o semarray_io_linker.o semundolst_io_linker.o sem_handler.o shmid_io_linker.o shm_memory_linker.o shm_handler.o
+obj-$(CONFIG_KRG_IPC_EPM) += krgipc_mobility.o ipc_checkpoint.o
